# 1. Activar la localización de la Wallet (Descomenta esta línea y pon la ruta de Docker)
oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/app/Wallet)))

# Activar JKS
javax.net.ssl.trustStore=${TNS_ADMIN}/truststore.jks
javax.net.ssl.trustStorePassword=FullStack-001
javax.net.ssl.keyStore=${TNS_ADMIN}/keystore.jks
javax.net.ssl.keyStorePassword=FullStack-001
