# 1. Activar la localización de la Wallet (Descomenta esta línea y pon la ruta de Docker)
# oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/app/Wallet)))

# 2. Activar JKS
javax.net.ssl.trustStore=/app/Wallet/truststore.jks
javax.net.ssl.trustStorePassword=FullStack-001
javax.net.ssl.keyStore=/app/Wallet/keystore.jks
javax.net.ssl.keyStorePassword=FullStack-001