spring:
  application:
    name: disponibilidadProfesional
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-hvy0.onrender.com/eureka/}
  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html